### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by alagiesellu** [manowartop97/repository-service-laravel-pattern#1]
Seems you started implementing the search feature on the `getAll` & `getAllPaginated`.

I have already had a similar implementation of this pattern where I have the search implemented. 

Want to contribute.

**Comment by manowartop97** [comment]
@alagiesellu hi, the search feature is not going to be implemented, the idea was to implement filtering in the repository function  ' protected function getFilteredQuery(array $search = []): Builder'.

And the getAll and getAllPaginated only using the returned builder from getFilteredQuery to return the result.

**Comment by alagiesellu** [comment]
So meaning anyone using the code won't be ables to inject search queries to the getAll and the getAllPaginated?

**Comment by manowartop97** [comment]
You can implement search in the repository method below

` protected function getFilteredQuery(array $search = []): Builder
    {
        return $this->getQuery()
            ->when(isset($search['ids']), function (Builder $query) use ($search) {
                $query->whereIn('id', $search['ids']);
            })
            ->when(isset($search['is_active']), function (Builder $query) use ($search) {
                $query->where('is_active', $search['is_active']);
            })
            ->orderBy('id', 'asc');
    }`
